### PR TITLE
Rename timecalc.py to timecalc

### PR DESCRIPTION
**Pull request by chapmanjacobd**
```
Building wheels for collected packages: timecalc
  Building wheel for timecalc (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      creating build
      running build_scripts
      creating build
      creating build/scripts-3.11
      error: [Errno 2] No such file or directory: 'timecalc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for timecalc
  Running setup.py clean for timecalc
Failed to build timecalc
ERROR: Could not build wheels for timecalc, which is required to install pyproject.toml-based projects
```

After renaming the file then `pip install .` works fine

### CODE REVIEW

**Comment by hydrargyrum** [comment]
Thank you! Btw, I will switch to `pyproject.toml` soon.

**Comment by chapmanjacobd** [comment]
here's an example with automatic deploy to pypi. might be helpful. just delete the stuff you don't need

https://github.com/chapmanjacobd/library/blob/main/pyproject.toml

https://github.com/chapmanjacobd/library/blob/main/.github/workflows/push.yaml

**Comment by hydrargyrum** [comment]
Unfortunately, the name "timecalc" is already taken on pypi. Have you got any suggestions for naming mine?

Thanks for the config, I prefer hosting CI on gitlab though (and am more familiar with it). But those examples are good!

**Comment by hydrargyrum** [comment]
Good, there it is: https://pypi.org/project/chronocalc/

I'll rename the repository later.

**Pull request merged**
